version: '3.8'  # Specify the Compose file version

services:
  app:
    container_name: finaillm-ingestion
    # image: finaillm-backend:latest  # Replace with your actual image
    build: 
      image: finaillm-ingestion:latest
      context: .
    environment:                     # Define environment variables here
      OPENAI_TOOL_LLM_NAME: gpt-3.5-turbo  # Corrected syntax for key-value pairs
      MONGODB_URI: ${MONGODB_URI}
      OPENAI_API_KEY: ${OPENAI_API_KEY}                    # Directory containing your Dockerfile
    volumes:
      - ./data:/data
    ports:
      - "8001:8000"                 # Map ports as needed